# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('like', models.CharField(choices=[('Document Scolaire', 'Document Scolaire'), ('Document Professionnel', 'Document Professionnel')], default='Document Scolaire', max_length=100)),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('comment', models.TextField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
            ],
            options={
                'db_table': 'SubmitDoc',
            },
        ),
    ]
