# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitdoc',
            old_name='fname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='submitdoc',
            old_name='lname',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='submitdoc',
            name='document',
        ),
        migrations.AddField(
            model_name='submitdoc',
            name='uploadDoc',
            field=models.FileField(default=12, upload_to='toberead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitdoc',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='submitdoc',
            table=None,
        ),
    ]
