# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francais', '0003_auto_20170211_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('uploadDoc', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('comment', models.TextField()),
            ],
        ),
    ]
