# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francais', '0004_submitdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitdoc',
            name='uploadDoc',
            field=models.FileField(upload_to=''),
        ),
    ]
