# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('francais', '0005_auto_20170215_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitdoc',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitdoc',
            name='like',
            field=models.BooleanField(default=0, verbose_name='like'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitdoc',
            name='uploadDoc',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
