# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('francais', '0007_auto_20170215_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitdoc',
            name='like',
        ),
    ]
