# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francais', '0009_auto_20170215_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitdoc',
            name='finished_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitdoc',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitdoc',
            name='read_by',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
